### ISSUE TITLE
Set `fname` to PDFCrowd filename by default

### ISSUE THREAD

**Issue by mchelen** [pdfcrowd/pdfcrowd-nodejs#6]
The `fname` parameter can be confusing because the PDFCrowd API has its own `pdf_name` setting. 
https://github.com/pdfcrowd/node-pdfcrowd/blob/master/lib/pdfcrowd.js#L107
https://pdfcrowd.com/html-to-pdf-api/#api-reference

It would be nice if somehow `fname` could use the PDFCrowd filename by default instead of `generated.pdf` with the function parameter used as an override.

**Comment by foxmadr** [comment]
Solved
