### ISSUE TITLE
what is the response variable being passed?

### ISSUE THREAD

**Issue by kcabading** [pdfcrowd/pdfcrowd-nodejs#8]
In the code below, where do I get the response variable being passed to sendHttpResponse?

`var pdf = require('pdfcrowd');

var client = new pdf.Pdfcrowd('username', 'apikey');
client.convertHtml('<html>regular HTML code</html>', pdf.sendHttpResponse(**response**));`

**Comment by foxmadr** [comment]
Please try the new API if it resolves your issue. Some samples are here:
[https://pdfcrowd.com/doc/api/html-to-pdf/nodejs/#examples-url-to-pdf](https://pdfcrowd.com/doc/api/html-to-pdf/nodejs/#examples-url-to-pdf)

**Comment by foxmadr** [comment]
Closed due to long inactivity
