### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by virtualLast** [pdfcrowd/pdfcrowd-nodejs#9]
I seem to be getting errors related to CORS, is CORS enabled? Code im using is below, this was all tested and working in Postman, but once added to javascript file and attached to button onclick event just gives errors

```
var settings = {
			"async": true,
			"crossDomain": true,
			"url": "http://pdfcrowd.com/api/pdf/convert/html/",
			"method": "POST",
			"headers": {
				"cache-control": "no-cache",
				"content-type": "application/x-www-form-urlencoded",
				'Access-Control-Allow-Origin': '*',
			},
			"data": {
				"username": "{inset username here}",
				"key": "{insert key here}",
				"src": "<html><h2 style=\"color: red;\">Title here</h2></html>"
			},
			"error": function(error) {
				console.log('we have had an error ' + error.statusText);
			}
		}

		$.ajax(settings).done(function (response) {
			console.log(response);
		});
```

**Comment by heisian** [comment]
You might need to set the Content Security Policy of your own client to allow AJAX requests to other domains.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

**Comment by foxmadr** [comment]
Please try the new API if it resolves your issue:
[https://pdfcrowd.com/doc/api/html-to-pdf/nodejs/](https://pdfcrowd.com/doc/api/html-to-pdf/nodejs/)

**Comment by foxmadr** [comment]
closed due to long inactivity
